// Generated by gencpp from file parking/car_state.msg
// DO NOT EDIT!


#ifndef PARKING_MESSAGE_CAR_STATE_H
#define PARKING_MESSAGE_CAR_STATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace parking
{
template <class ContainerAllocator>
struct car_state_
{
  typedef car_state_<ContainerAllocator> Type;

  car_state_()
    : x()
    , y()
    , psi()
    , v()  {
    }
  car_state_(const ContainerAllocator& _alloc)
    : x(_alloc)
    , y(_alloc)
    , psi(_alloc)
    , v(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _x_type;
  _x_type x;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _y_type;
  _y_type y;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _psi_type;
  _psi_type psi;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _v_type;
  _v_type v;





  typedef boost::shared_ptr< ::parking::car_state_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::parking::car_state_<ContainerAllocator> const> ConstPtr;

}; // struct car_state_

typedef ::parking::car_state_<std::allocator<void> > car_state;

typedef boost::shared_ptr< ::parking::car_state > car_statePtr;
typedef boost::shared_ptr< ::parking::car_state const> car_stateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::parking::car_state_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::parking::car_state_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace parking

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'parking': ['/home/xushen/Multi_Car_Parking/workspace/src/parking/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::parking::car_state_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::parking::car_state_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::parking::car_state_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::parking::car_state_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::parking::car_state_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::parking::car_state_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::parking::car_state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "46770b25fddd17772c0c599a8d50502a";
  }

  static const char* value(const ::parking::car_state_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x46770b25fddd1777ULL;
  static const uint64_t static_value2 = 0x2c0c599a8d50502aULL;
};

template<class ContainerAllocator>
struct DataType< ::parking::car_state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "parking/car_state";
  }

  static const char* value(const ::parking::car_state_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::parking::car_state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# The states used in vehicle control\n\
# x, y, heading and speed\n\
float64[] x\n\
float64[] y\n\
float64[] psi\n\
float64[] v\n\
";
  }

  static const char* value(const ::parking::car_state_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::parking::car_state_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.psi);
      stream.next(m.v);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct car_state_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::parking::car_state_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::parking::car_state_<ContainerAllocator>& v)
  {
    s << indent << "x[]" << std::endl;
    for (size_t i = 0; i < v.x.size(); ++i)
    {
      s << indent << "  x[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.x[i]);
    }
    s << indent << "y[]" << std::endl;
    for (size_t i = 0; i < v.y.size(); ++i)
    {
      s << indent << "  y[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.y[i]);
    }
    s << indent << "psi[]" << std::endl;
    for (size_t i = 0; i < v.psi.size(); ++i)
    {
      s << indent << "  psi[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.psi[i]);
    }
    s << indent << "v[]" << std::endl;
    for (size_t i = 0; i < v.v.size(); ++i)
    {
      s << indent << "  v[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.v[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PARKING_MESSAGE_CAR_STATE_H
