// Generated by gencpp from file parking/car_input.msg
// DO NOT EDIT!


#ifndef PARKING_MESSAGE_CAR_INPUT_H
#define PARKING_MESSAGE_CAR_INPUT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace parking
{
template <class ContainerAllocator>
struct car_input_
{
  typedef car_input_<ContainerAllocator> Type;

  car_input_()
    : delta()
    , acc()  {
    }
  car_input_(const ContainerAllocator& _alloc)
    : delta(_alloc)
    , acc(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _delta_type;
  _delta_type delta;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _acc_type;
  _acc_type acc;





  typedef boost::shared_ptr< ::parking::car_input_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::parking::car_input_<ContainerAllocator> const> ConstPtr;

}; // struct car_input_

typedef ::parking::car_input_<std::allocator<void> > car_input;

typedef boost::shared_ptr< ::parking::car_input > car_inputPtr;
typedef boost::shared_ptr< ::parking::car_input const> car_inputConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::parking::car_input_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::parking::car_input_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace parking

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'parking': ['/home/xushen/Multi_Car_Parking/workspace/src/parking/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::parking::car_input_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::parking::car_input_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::parking::car_input_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::parking::car_input_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::parking::car_input_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::parking::car_input_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::parking::car_input_<ContainerAllocator> >
{
  static const char* value()
  {
    return "abdc68e560ea7f4923b164eecfe49022";
  }

  static const char* value(const ::parking::car_input_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xabdc68e560ea7f49ULL;
  static const uint64_t static_value2 = 0x23b164eecfe49022ULL;
};

template<class ContainerAllocator>
struct DataType< ::parking::car_input_<ContainerAllocator> >
{
  static const char* value()
  {
    return "parking/car_input";
  }

  static const char* value(const ::parking::car_input_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::parking::car_input_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# The input used in vehicle control\n\
# Steering angle and acceleration\n\
float64[] delta\n\
float64[] acc\n\
";
  }

  static const char* value(const ::parking::car_input_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::parking::car_input_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.delta);
      stream.next(m.acc);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct car_input_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::parking::car_input_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::parking::car_input_<ContainerAllocator>& v)
  {
    s << indent << "delta[]" << std::endl;
    for (size_t i = 0; i < v.delta.size(); ++i)
    {
      s << indent << "  delta[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.delta[i]);
    }
    s << indent << "acc[]" << std::endl;
    for (size_t i = 0; i < v.acc.size(); ++i)
    {
      s << indent << "  acc[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.acc[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PARKING_MESSAGE_CAR_INPUT_H
