// Generated by gencpp from file parking/maneuver.msg
// DO NOT EDIT!


#ifndef PARKING_MESSAGE_MANEUVER_H
#define PARKING_MESSAGE_MANEUVER_H

#include <ros/service_traits.h>


#include <parking/maneuverRequest.h>
#include <parking/maneuverResponse.h>


namespace parking
{

struct maneuver
{

typedef maneuverRequest Request;
typedef maneuverResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct maneuver
} // namespace parking


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::parking::maneuver > {
  static const char* value()
  {
    return "946fe324ce1d28d42fa3b8f242a28b5c";
  }

  static const char* value(const ::parking::maneuver&) { return value(); }
};

template<>
struct DataType< ::parking::maneuver > {
  static const char* value()
  {
    return "parking/maneuver";
  }

  static const char* value(const ::parking::maneuver&) { return value(); }
};


// service_traits::MD5Sum< ::parking::maneuverRequest> should match 
// service_traits::MD5Sum< ::parking::maneuver > 
template<>
struct MD5Sum< ::parking::maneuverRequest>
{
  static const char* value()
  {
    return MD5Sum< ::parking::maneuver >::value();
  }
  static const char* value(const ::parking::maneuverRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::parking::maneuverRequest> should match 
// service_traits::DataType< ::parking::maneuver > 
template<>
struct DataType< ::parking::maneuverRequest>
{
  static const char* value()
  {
    return DataType< ::parking::maneuver >::value();
  }
  static const char* value(const ::parking::maneuverRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::parking::maneuverResponse> should match 
// service_traits::MD5Sum< ::parking::maneuver > 
template<>
struct MD5Sum< ::parking::maneuverResponse>
{
  static const char* value()
  {
    return MD5Sum< ::parking::maneuver >::value();
  }
  static const char* value(const ::parking::maneuverResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::parking::maneuverResponse> should match 
// service_traits::DataType< ::parking::maneuver > 
template<>
struct DataType< ::parking::maneuverResponse>
{
  static const char* value()
  {
    return DataType< ::parking::maneuver >::value();
  }
  static const char* value(const ::parking::maneuverResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PARKING_MESSAGE_MANEUVER_H
