// Generated by gencpp from file parking/park_maneuverRequest.msg
// DO NOT EDIT!


#ifndef PARKING_MESSAGE_PARK_MANEUVERREQUEST_H
#define PARKING_MESSAGE_PARK_MANEUVERREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace parking
{
template <class ContainerAllocator>
struct park_maneuverRequest_
{
  typedef park_maneuverRequest_<ContainerAllocator> Type;

  park_maneuverRequest_()
    : Start_lane()
    , End_spot()
    , End_pose()  {
    }
  park_maneuverRequest_(const ContainerAllocator& _alloc)
    : Start_lane(_alloc)
    , End_spot(_alloc)
    , End_pose(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _Start_lane_type;
  _Start_lane_type Start_lane;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _End_spot_type;
  _End_spot_type End_spot;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _End_pose_type;
  _End_pose_type End_pose;





  typedef boost::shared_ptr< ::parking::park_maneuverRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::parking::park_maneuverRequest_<ContainerAllocator> const> ConstPtr;

}; // struct park_maneuverRequest_

typedef ::parking::park_maneuverRequest_<std::allocator<void> > park_maneuverRequest;

typedef boost::shared_ptr< ::parking::park_maneuverRequest > park_maneuverRequestPtr;
typedef boost::shared_ptr< ::parking::park_maneuverRequest const> park_maneuverRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::parking::park_maneuverRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::parking::park_maneuverRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace parking

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::parking::park_maneuverRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::parking::park_maneuverRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::parking::park_maneuverRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::parking::park_maneuverRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::parking::park_maneuverRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::parking::park_maneuverRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::parking::park_maneuverRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a95a3873c578d430d5049d20303c042d";
  }

  static const char* value(const ::parking::park_maneuverRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa95a3873c578d430ULL;
  static const uint64_t static_value2 = 0xd5049d20303c042dULL;
};

template<class ContainerAllocator>
struct DataType< ::parking::park_maneuverRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "parking/park_maneuverRequest";
  }

  static const char* value(const ::parking::park_maneuverRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::parking::park_maneuverRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string Start_lane\n\
string End_spot\n\
string End_pose\n\
";
  }

  static const char* value(const ::parking::park_maneuverRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::parking::park_maneuverRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Start_lane);
      stream.next(m.End_spot);
      stream.next(m.End_pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct park_maneuverRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::parking::park_maneuverRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::parking::park_maneuverRequest_<ContainerAllocator>& v)
  {
    s << indent << "Start_lane: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.Start_lane);
    s << indent << "End_spot: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.End_spot);
    s << indent << "End_pose: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.End_pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PARKING_MESSAGE_PARK_MANEUVERREQUEST_H
