// Generated by gencpp from file parking/park_maneuver.msg
// DO NOT EDIT!


#ifndef PARKING_MESSAGE_PARK_MANEUVER_H
#define PARKING_MESSAGE_PARK_MANEUVER_H

#include <ros/service_traits.h>


#include <parking/park_maneuverRequest.h>
#include <parking/park_maneuverResponse.h>


namespace parking
{

struct park_maneuver
{

typedef park_maneuverRequest Request;
typedef park_maneuverResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct park_maneuver
} // namespace parking


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::parking::park_maneuver > {
  static const char* value()
  {
    return "a22294d83207313cb1c3be5a262be07d";
  }

  static const char* value(const ::parking::park_maneuver&) { return value(); }
};

template<>
struct DataType< ::parking::park_maneuver > {
  static const char* value()
  {
    return "parking/park_maneuver";
  }

  static const char* value(const ::parking::park_maneuver&) { return value(); }
};


// service_traits::MD5Sum< ::parking::park_maneuverRequest> should match 
// service_traits::MD5Sum< ::parking::park_maneuver > 
template<>
struct MD5Sum< ::parking::park_maneuverRequest>
{
  static const char* value()
  {
    return MD5Sum< ::parking::park_maneuver >::value();
  }
  static const char* value(const ::parking::park_maneuverRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::parking::park_maneuverRequest> should match 
// service_traits::DataType< ::parking::park_maneuver > 
template<>
struct DataType< ::parking::park_maneuverRequest>
{
  static const char* value()
  {
    return DataType< ::parking::park_maneuver >::value();
  }
  static const char* value(const ::parking::park_maneuverRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::parking::park_maneuverResponse> should match 
// service_traits::MD5Sum< ::parking::park_maneuver > 
template<>
struct MD5Sum< ::parking::park_maneuverResponse>
{
  static const char* value()
  {
    return MD5Sum< ::parking::park_maneuver >::value();
  }
  static const char* value(const ::parking::park_maneuverResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::parking::park_maneuverResponse> should match 
// service_traits::DataType< ::parking::park_maneuver > 
template<>
struct DataType< ::parking::park_maneuverResponse>
{
  static const char* value()
  {
    return DataType< ::parking::park_maneuver >::value();
  }
  static const char* value(const ::parking::park_maneuverResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PARKING_MESSAGE_PARK_MANEUVER_H
